### PR TITLE
fix: send just activation stats

### LINKED ISSUE #121: Observabiliy: send stats only
Send only activation stats in case of every state:
- failed
- skipped
- completed

### PR DESCRIPTION
**Pull request by dicagno**
fix #121

### CODE REVIEW

File: actions/lib/observability.js [hunk 1]
```diff
@@ -37,70 +37,47 @@ class ObservabilityClient {
...
+      'DEBUG': 1,
+      'VERBOSE': 2,
+      'INFO': 3,
+      'WARNING': 4,
+      'ERROR': 5,
+      'CRITICAL': 6,
+    }
+
+    stateToSeverity(state) {
+      const stateToSeverityMap = {
```
Comment (buuhuu) [inline actions/lib/observability.js:50]: would it make sense to flag completed activations as `ERROR` in case there is at least one failed path?
